---
title: "Final Project"
format: html
editor: visual
---

```{r}
#| echo: false
#| warning: false
remotes::install_github("higgi13425/medicaldata")
library(medicaldata)
library(readr)
library(gtsummary)
cytomeg <- medicaldata::cytomegalovirus

```

```{r}
#| label: desc-tbl
#| tbl-cap: "Table 1"
#| echo: false
#| warning: false

desc_stats<- tbl_summary(
cytomeg, 
by = sex,
include = c(
	diagnosis.type, prior.radiation, prior.chemo, cmv, time.to.cmv
),
label = list(
	diagnosis.type ~ "Type of Diagnosis (0 = lymphoid, 1 = myeloid)",
	prior.radiation ~ "Prior radiation (0 = no, 1 = yes)",
	time.to.cmv ~ "Time to CMV reactivation (in months)",
	cmv ~ "Cytomegalovirus reactivation posttransplant (0 = no, 1 = yes)",
	prior.chemo ~ "Number of prior chemotherapy regimens"
),   missing_text = "Missing"
) |>
		add_p(test = list(
			all_continuous() ~ "t.test",
			all_categorical() ~ "chisq.test"
		)) |>
		add_overall(col_label = "**Total** N = {N}") |>
		bold_labels()

desc_stats
```

```{r}
#|label: reg_tbl
#|tbl-cap: "Table 2 (Regression)"
#|echo: false

regress<- tbl_uvregression(
	cytomeg,
	y = prior.chemo,
	include = c(time.to.cmv, cmv, diagnosis.type),
	method = lm
)

regress
inline_text(regress, variable = "cmv")
```

```{r}
#| label: figure
#| fig-cap: "Figure 1"
#| echo: false

fig_one<-hist(cytomeg$time.to.cmv, main = "Time to CMV Reactivation", xlab = "Months",
		 col = "navy")
```

```{r}

timeto_med<-inline_text(desc_stats, variable = "time.to.cmv", 
						pattern = "{median} months")


```


